FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /bot

COPY bot/requirements.txt /bot/requirements.txt
RUN pip install --no-cache-dir -r /bot/requirements.txt

COPY bot /bot

CMD ["python", "main.py"]
