"""Changed types of micronutrients for numeric

Revision ID: 98dc8ad757c6
Revises: f958588739f8
Create Date: 2026-02-06 16:35:14.315712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98dc8ad757c6"
down_revision: Union[str, Sequence[str], None] = "f958588739f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meal_entry",
        "protein",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=6, scale=1),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_entry",
        "fat",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=6, scale=1),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_entry",
        "carbs",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=6, scale=1),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_entry",
        "confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meal_entry",
        "confidence",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "meal_entry",
        "carbs",
        existing_type=sa.Numeric(precision=6, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_entry",
        "fat",
        existing_type=sa.Numeric(precision=6, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "meal_entry",
        "protein",
        existing_type=sa.Numeric(precision=6, scale=1),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
