"""Initial schema

Revision ID: caa9722022e6
Revises:
Create Date: 2026-02-05 16:20:05.146978

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caa9722022e6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_user_id"),
    )
    op.create_table(
        "meal_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein", sa.Integer(), nullable=True),
        sa.Column("fat", sa.Integer(), nullable=True),
        sa.Column("carbs", sa.Integer(), nullable=True),
        sa.Column(
            "llm_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_user.tg_user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "tg_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "tg_user_id",
            name=op.f("user_tg_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("meal_entry")
    op.drop_table("tg_user")
    # ### end Alembic commands ###
