"""Added field 'created_at'

Revision ID: f958588739f8
Revises: caa9722022e6
Create Date: 2026-02-06 09:23:28.406090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f958588739f8'
down_revision: Union[str, Sequence[str], None] = 'caa9722022e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_entry', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_entry', 'created_at')
    # ### end Alembic commands ###
